name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositorio
      uses: actions/checkout@v3

    - name: Instalar Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Instalar dependencias
      run: |
        pip install flake8

    - name: Verificar formato con flake8
      run: |
        flake8 main.py estudiantes/

    - name: Ejecutar el programa
      run: |
        python main.py
